server:
  port: 8081

spring:
  application:
    name: pii-service

logging:
  level:
    com.securegenai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
